apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-app-deployment
  labels:
    app: prometheus-app
spec:
  replicas: 3 # Chạy 3 Pod
  selector:
    matchLabels:
      app: prometheus-app
  template:
    metadata:
      labels:
        app: prometheus-app
    spec:
      containers:
        - name: prometheus-app
          # SỬ DỤNG TÊN IMAGE CỦA BẠN VỪA PUSH
          image: danny078/prometheus-app:latest
          ports:
            - containerPort: 8080 # Cổng mặc định của Spring Boot
          # Thêm readiness/liveness probes nếu cần