apiVersion: v1
kind: Service
metadata:
  name: prometheus-app-service
  labels:
    app: prometheus-app
spec:
  selector:
    app: prometheus-app
  ports:
    - protocol: TCP
      port: 80 # Cổng Service (ví dụ: truy cập bên ngoài)
      targetPort: 8080 # Cổng ứng dụng Spring Boot (bên trong container)
  type: LoadBalancer # Hoặc NodePort nếu bạn triển khai trên K8s local (Minikube)